'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace JpocWeb.EditorService
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://clinicalsup.jp/", ConfigurationName:="JpocWeb.EditorService.EditorServiceSoap")>  _
    Public Interface EditorServiceSoap
        
        'CODEGEN: Generating message contract since element name pUserID from namespace http://clinicalsup.jp/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://clinicalsup.jp/Authorize", ReplyAction:="*")>  _
        Function Authorize(ByVal request As JpocWeb.EditorService.AuthorizeRequest) As JpocWeb.EditorService.AuthorizeResponse
        
        'CODEGEN: Generating message contract since element name pUserID from namespace http://clinicalsup.jp/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://clinicalsup.jp/GetDiseaseList", ReplyAction:="*")>  _
        Function GetDiseaseList(ByVal request As JpocWeb.EditorService.GetDiseaseListRequest) As JpocWeb.EditorService.GetDiseaseListResponse
        
        'CODEGEN: Generating message contract since element name pUserID from namespace http://clinicalsup.jp/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://clinicalsup.jp/GetDiseaseData", ReplyAction:="*")>  _
        Function GetDiseaseData(ByVal request As JpocWeb.EditorService.GetDiseaseDataRequest) As JpocWeb.EditorService.GetDiseaseDataResponse
        
        'CODEGEN: Generating message contract since element name pUserID from namespace http://clinicalsup.jp/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://clinicalsup.jp/UpdateDisease", ReplyAction:="*")>  _
        Function UpdateDisease(ByVal request As JpocWeb.EditorService.UpdateDiseaseRequest) As JpocWeb.EditorService.UpdateDiseaseResponse
        
        'CODEGEN: Generating message contract since element name pUserID from namespace http://clinicalsup.jp/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://clinicalsup.jp/GetDataToDataSet", ReplyAction:="*")>  _
        Function GetDataToDataSet(ByVal request As JpocWeb.EditorService.GetDataToDataSetRequest) As JpocWeb.EditorService.GetDataToDataSetResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class AuthorizeRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Authorize", [Namespace]:="http://clinicalsup.jp/", Order:=0)>  _
        Public Body As JpocWeb.EditorService.AuthorizeRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As JpocWeb.EditorService.AuthorizeRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://clinicalsup.jp/")>  _
    Partial Public Class AuthorizeRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public pUserID As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public pInstitutionCode As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public pPassword As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=3)>  _
        Public RtnCD As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public RtnMsg As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal pUserID As String, ByVal pInstitutionCode As String, ByVal pPassword As String, ByVal RtnCD As Integer, ByVal RtnMsg As String)
            MyBase.New
            Me.pUserID = pUserID
            Me.pInstitutionCode = pInstitutionCode
            Me.pPassword = pPassword
            Me.RtnCD = RtnCD
            Me.RtnMsg = RtnMsg
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class AuthorizeResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="AuthorizeResponse", [Namespace]:="http://clinicalsup.jp/", Order:=0)>  _
        Public Body As JpocWeb.EditorService.AuthorizeResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As JpocWeb.EditorService.AuthorizeResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://clinicalsup.jp/")>  _
    Partial Public Class AuthorizeResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public AuthorizeResult As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public RtnCD As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public RtnMsg As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal AuthorizeResult As Boolean, ByVal RtnCD As Integer, ByVal RtnMsg As String)
            MyBase.New
            Me.AuthorizeResult = AuthorizeResult
            Me.RtnCD = RtnCD
            Me.RtnMsg = RtnMsg
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetDiseaseListRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetDiseaseList", [Namespace]:="http://clinicalsup.jp/", Order:=0)>  _
        Public Body As JpocWeb.EditorService.GetDiseaseListRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As JpocWeb.EditorService.GetDiseaseListRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://clinicalsup.jp/")>  _
    Partial Public Class GetDiseaseListRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public pUserID As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public pInstitutionCode As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public pPassword As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=3)>  _
        Public RtnCD As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public RtnMsg As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal pUserID As String, ByVal pInstitutionCode As String, ByVal pPassword As String, ByVal RtnCD As Integer, ByVal RtnMsg As String)
            MyBase.New
            Me.pUserID = pUserID
            Me.pInstitutionCode = pInstitutionCode
            Me.pPassword = pPassword
            Me.RtnCD = RtnCD
            Me.RtnMsg = RtnMsg
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetDiseaseListResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetDiseaseListResponse", [Namespace]:="http://clinicalsup.jp/", Order:=0)>  _
        Public Body As JpocWeb.EditorService.GetDiseaseListResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As JpocWeb.EditorService.GetDiseaseListResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://clinicalsup.jp/")>  _
    Partial Public Class GetDiseaseListResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetDiseaseListResult() As Byte
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public RtnCD As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public RtnMsg As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetDiseaseListResult() As Byte, ByVal RtnCD As Integer, ByVal RtnMsg As String)
            MyBase.New
            Me.GetDiseaseListResult = GetDiseaseListResult
            Me.RtnCD = RtnCD
            Me.RtnMsg = RtnMsg
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetDiseaseDataRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetDiseaseData", [Namespace]:="http://clinicalsup.jp/", Order:=0)>  _
        Public Body As JpocWeb.EditorService.GetDiseaseDataRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As JpocWeb.EditorService.GetDiseaseDataRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://clinicalsup.jp/")>  _
    Partial Public Class GetDiseaseDataRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public pUserID As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public pInstitutionCode As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public pPassword As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public pDiseaseID As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=4)>  _
        Public pWithoutPopupContents As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=5)>  _
        Public pOnlyRawImage As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=6)>  _
        Public pNeedBase64Encode As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=7)>  _
        Public RtnCD As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=8)>  _
        Public RtnMsg As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal pUserID As String, ByVal pInstitutionCode As String, ByVal pPassword As String, ByVal pDiseaseID As String, ByVal pWithoutPopupContents As Boolean, ByVal pOnlyRawImage As Boolean, ByVal pNeedBase64Encode As Boolean, ByVal RtnCD As Integer, ByVal RtnMsg As String)
            MyBase.New
            Me.pUserID = pUserID
            Me.pInstitutionCode = pInstitutionCode
            Me.pPassword = pPassword
            Me.pDiseaseID = pDiseaseID
            Me.pWithoutPopupContents = pWithoutPopupContents
            Me.pOnlyRawImage = pOnlyRawImage
            Me.pNeedBase64Encode = pNeedBase64Encode
            Me.RtnCD = RtnCD
            Me.RtnMsg = RtnMsg
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetDiseaseDataResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetDiseaseDataResponse", [Namespace]:="http://clinicalsup.jp/", Order:=0)>  _
        Public Body As JpocWeb.EditorService.GetDiseaseDataResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As JpocWeb.EditorService.GetDiseaseDataResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://clinicalsup.jp/")>  _
    Partial Public Class GetDiseaseDataResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetDiseaseDataResult() As Byte
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public RtnCD As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public RtnMsg As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetDiseaseDataResult() As Byte, ByVal RtnCD As Integer, ByVal RtnMsg As String)
            MyBase.New
            Me.GetDiseaseDataResult = GetDiseaseDataResult
            Me.RtnCD = RtnCD
            Me.RtnMsg = RtnMsg
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class UpdateDiseaseRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="UpdateDisease", [Namespace]:="http://clinicalsup.jp/", Order:=0)>  _
        Public Body As JpocWeb.EditorService.UpdateDiseaseRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As JpocWeb.EditorService.UpdateDiseaseRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://clinicalsup.jp/")>  _
    Partial Public Class UpdateDiseaseRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public pUserID As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public pInstitutionCode As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public pPassword As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public pDiseaseID As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public pDiseaseData() As Byte
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=5)>  _
        Public pNeedBase64Encode As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=6)>  _
        Public RtnCD As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=7)>  _
        Public RtnMsg As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal pUserID As String, ByVal pInstitutionCode As String, ByVal pPassword As String, ByVal pDiseaseID As String, ByVal pDiseaseData() As Byte, ByVal pNeedBase64Encode As Boolean, ByVal RtnCD As Integer, ByVal RtnMsg As String)
            MyBase.New
            Me.pUserID = pUserID
            Me.pInstitutionCode = pInstitutionCode
            Me.pPassword = pPassword
            Me.pDiseaseID = pDiseaseID
            Me.pDiseaseData = pDiseaseData
            Me.pNeedBase64Encode = pNeedBase64Encode
            Me.RtnCD = RtnCD
            Me.RtnMsg = RtnMsg
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class UpdateDiseaseResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="UpdateDiseaseResponse", [Namespace]:="http://clinicalsup.jp/", Order:=0)>  _
        Public Body As JpocWeb.EditorService.UpdateDiseaseResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As JpocWeb.EditorService.UpdateDiseaseResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://clinicalsup.jp/")>  _
    Partial Public Class UpdateDiseaseResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public RtnCD As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public RtnMsg As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal RtnCD As Integer, ByVal RtnMsg As String)
            MyBase.New
            Me.RtnCD = RtnCD
            Me.RtnMsg = RtnMsg
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetDataToDataSetRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetDataToDataSet", [Namespace]:="http://clinicalsup.jp/", Order:=0)>  _
        Public Body As JpocWeb.EditorService.GetDataToDataSetRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As JpocWeb.EditorService.GetDataToDataSetRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://clinicalsup.jp/")>  _
    Partial Public Class GetDataToDataSetRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public pUserID As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public pInstitutionCode As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public pPassword As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public pSql As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=4)>  _
        Public RtnCD As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public RtnMsg As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal pUserID As String, ByVal pInstitutionCode As String, ByVal pPassword As String, ByVal pSql As String, ByVal RtnCD As Integer, ByVal RtnMsg As String)
            MyBase.New
            Me.pUserID = pUserID
            Me.pInstitutionCode = pInstitutionCode
            Me.pPassword = pPassword
            Me.pSql = pSql
            Me.RtnCD = RtnCD
            Me.RtnMsg = RtnMsg
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetDataToDataSetResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetDataToDataSetResponse", [Namespace]:="http://clinicalsup.jp/", Order:=0)>  _
        Public Body As JpocWeb.EditorService.GetDataToDataSetResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As JpocWeb.EditorService.GetDataToDataSetResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://clinicalsup.jp/")>  _
    Partial Public Class GetDataToDataSetResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetDataToDataSetResult() As Byte
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public RtnCD As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public RtnMsg As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetDataToDataSetResult() As Byte, ByVal RtnCD As Integer, ByVal RtnMsg As String)
            MyBase.New
            Me.GetDataToDataSetResult = GetDataToDataSetResult
            Me.RtnCD = RtnCD
            Me.RtnMsg = RtnMsg
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface EditorServiceSoapChannel
        Inherits JpocWeb.EditorService.EditorServiceSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class EditorServiceSoapClient
        Inherits System.ServiceModel.ClientBase(Of JpocWeb.EditorService.EditorServiceSoap)
        Implements JpocWeb.EditorService.EditorServiceSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        'TODO: FIX HERE
        Public Sub New(ByVal endpointConfigurationName As String)
            'MyBase.New(endpointConfigurationName)
        End Sub
        'TODO: FIX HERE
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            'MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        'TODO: FIX HERE
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            'MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function JpocWeb_EditorService_EditorServiceSoap_Authorize(ByVal request As JpocWeb.EditorService.AuthorizeRequest) As JpocWeb.EditorService.AuthorizeResponse Implements JpocWeb.EditorService.EditorServiceSoap.Authorize
            Return MyBase.Channel.Authorize(request)
        End Function
        
        Public Function Authorize(ByVal pUserID As String, ByVal pInstitutionCode As String, ByVal pPassword As String, ByRef RtnCD As Integer, ByRef RtnMsg As String) As Boolean
            Dim inValue As JpocWeb.EditorService.AuthorizeRequest = New JpocWeb.EditorService.AuthorizeRequest()
            inValue.Body = New JpocWeb.EditorService.AuthorizeRequestBody()
            inValue.Body.pUserID = pUserID
            inValue.Body.pInstitutionCode = pInstitutionCode
            inValue.Body.pPassword = pPassword
            inValue.Body.RtnCD = RtnCD
            inValue.Body.RtnMsg = RtnMsg
            Dim retVal As JpocWeb.EditorService.AuthorizeResponse = CType(Me,JpocWeb.EditorService.EditorServiceSoap).Authorize(inValue)
            RtnCD = retVal.Body.RtnCD
            RtnMsg = retVal.Body.RtnMsg
            Return retVal.Body.AuthorizeResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function JpocWeb_EditorService_EditorServiceSoap_GetDiseaseList(ByVal request As JpocWeb.EditorService.GetDiseaseListRequest) As JpocWeb.EditorService.GetDiseaseListResponse Implements JpocWeb.EditorService.EditorServiceSoap.GetDiseaseList
            Return MyBase.Channel.GetDiseaseList(request)
        End Function
        
        Public Function GetDiseaseList(ByVal pUserID As String, ByVal pInstitutionCode As String, ByVal pPassword As String, ByRef RtnCD As Integer, ByRef RtnMsg As String) As Byte()
            Dim inValue As JpocWeb.EditorService.GetDiseaseListRequest = New JpocWeb.EditorService.GetDiseaseListRequest()
            inValue.Body = New JpocWeb.EditorService.GetDiseaseListRequestBody()
            inValue.Body.pUserID = pUserID
            inValue.Body.pInstitutionCode = pInstitutionCode
            inValue.Body.pPassword = pPassword
            inValue.Body.RtnCD = RtnCD
            inValue.Body.RtnMsg = RtnMsg
            Dim retVal As JpocWeb.EditorService.GetDiseaseListResponse = CType(Me,JpocWeb.EditorService.EditorServiceSoap).GetDiseaseList(inValue)
            RtnCD = retVal.Body.RtnCD
            RtnMsg = retVal.Body.RtnMsg
            Return retVal.Body.GetDiseaseListResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function JpocWeb_EditorService_EditorServiceSoap_GetDiseaseData(ByVal request As JpocWeb.EditorService.GetDiseaseDataRequest) As JpocWeb.EditorService.GetDiseaseDataResponse Implements JpocWeb.EditorService.EditorServiceSoap.GetDiseaseData
            Return MyBase.Channel.GetDiseaseData(request)
        End Function
        
        Public Function GetDiseaseData(ByVal pUserID As String, ByVal pInstitutionCode As String, ByVal pPassword As String, ByVal pDiseaseID As String, ByVal pWithoutPopupContents As Boolean, ByVal pOnlyRawImage As Boolean, ByVal pNeedBase64Encode As Boolean, ByRef RtnCD As Integer, ByRef RtnMsg As String) As Byte()
            Dim inValue As JpocWeb.EditorService.GetDiseaseDataRequest = New JpocWeb.EditorService.GetDiseaseDataRequest()
            inValue.Body = New JpocWeb.EditorService.GetDiseaseDataRequestBody()
            inValue.Body.pUserID = pUserID
            inValue.Body.pInstitutionCode = pInstitutionCode
            inValue.Body.pPassword = pPassword
            inValue.Body.pDiseaseID = pDiseaseID
            inValue.Body.pWithoutPopupContents = pWithoutPopupContents
            inValue.Body.pOnlyRawImage = pOnlyRawImage
            inValue.Body.pNeedBase64Encode = pNeedBase64Encode
            inValue.Body.RtnCD = RtnCD
            inValue.Body.RtnMsg = RtnMsg
            Dim retVal As JpocWeb.EditorService.GetDiseaseDataResponse = CType(Me,JpocWeb.EditorService.EditorServiceSoap).GetDiseaseData(inValue)
            RtnCD = retVal.Body.RtnCD
            RtnMsg = retVal.Body.RtnMsg
            Return retVal.Body.GetDiseaseDataResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function JpocWeb_EditorService_EditorServiceSoap_UpdateDisease(ByVal request As JpocWeb.EditorService.UpdateDiseaseRequest) As JpocWeb.EditorService.UpdateDiseaseResponse Implements JpocWeb.EditorService.EditorServiceSoap.UpdateDisease
            Return MyBase.Channel.UpdateDisease(request)
        End Function
        
        Public Sub UpdateDisease(ByVal pUserID As String, ByVal pInstitutionCode As String, ByVal pPassword As String, ByVal pDiseaseID As String, ByVal pDiseaseData() As Byte, ByVal pNeedBase64Encode As Boolean, ByRef RtnCD As Integer, ByRef RtnMsg As String)
            Dim inValue As JpocWeb.EditorService.UpdateDiseaseRequest = New JpocWeb.EditorService.UpdateDiseaseRequest()
            inValue.Body = New JpocWeb.EditorService.UpdateDiseaseRequestBody()
            inValue.Body.pUserID = pUserID
            inValue.Body.pInstitutionCode = pInstitutionCode
            inValue.Body.pPassword = pPassword
            inValue.Body.pDiseaseID = pDiseaseID
            inValue.Body.pDiseaseData = pDiseaseData
            inValue.Body.pNeedBase64Encode = pNeedBase64Encode
            inValue.Body.RtnCD = RtnCD
            inValue.Body.RtnMsg = RtnMsg
            Dim retVal As JpocWeb.EditorService.UpdateDiseaseResponse = CType(Me,JpocWeb.EditorService.EditorServiceSoap).UpdateDisease(inValue)
            RtnCD = retVal.Body.RtnCD
            RtnMsg = retVal.Body.RtnMsg
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function JpocWeb_EditorService_EditorServiceSoap_GetDataToDataSet(ByVal request As JpocWeb.EditorService.GetDataToDataSetRequest) As JpocWeb.EditorService.GetDataToDataSetResponse Implements JpocWeb.EditorService.EditorServiceSoap.GetDataToDataSet
            Return MyBase.Channel.GetDataToDataSet(request)
        End Function
        
        Public Function GetDataToDataSet(ByVal pUserID As String, ByVal pInstitutionCode As String, ByVal pPassword As String, ByVal pSql As String, ByRef RtnCD As Integer, ByRef RtnMsg As String) As Byte()
            Dim inValue As JpocWeb.EditorService.GetDataToDataSetRequest = New JpocWeb.EditorService.GetDataToDataSetRequest()
            inValue.Body = New JpocWeb.EditorService.GetDataToDataSetRequestBody()
            inValue.Body.pUserID = pUserID
            inValue.Body.pInstitutionCode = pInstitutionCode
            inValue.Body.pPassword = pPassword
            inValue.Body.pSql = pSql
            inValue.Body.RtnCD = RtnCD
            inValue.Body.RtnMsg = RtnMsg
            Dim retVal As JpocWeb.EditorService.GetDataToDataSetResponse = CType(Me,JpocWeb.EditorService.EditorServiceSoap).GetDataToDataSet(inValue)
            RtnCD = retVal.Body.RtnCD
            RtnMsg = retVal.Body.RtnMsg
            Return retVal.Body.GetDataToDataSetResult
        End Function
    End Class
End Namespace
