'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace JpocWeb.AdminService
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://clinicalsup.jp/", ConfigurationName:="JpocWeb.AdminService.AdminServiceSoap")>  _
    Public Interface AdminServiceSoap
        
        'CODEGEN: Generating message contract since element name pUserID from namespace http://clinicalsup.jp/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://clinicalsup.jp/GetDataToDataSet", ReplyAction:="*")>  _
        Function GetDataToDataSet(ByVal request As JpocWeb.AdminService.GetDataToDataSetRequest) As JpocWeb.AdminService.GetDataToDataSetResponse
        
        'CODEGEN: Generating message contract since element name pUserID from namespace http://clinicalsup.jp/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://clinicalsup.jp/ExecuteNoResult", ReplyAction:="*")>  _
        Function ExecuteNoResult(ByVal request As JpocWeb.AdminService.ExecuteNoResultRequest) As JpocWeb.AdminService.ExecuteNoResultResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetDataToDataSetRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetDataToDataSet", [Namespace]:="http://clinicalsup.jp/", Order:=0)>  _
        Public Body As JpocWeb.AdminService.GetDataToDataSetRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As JpocWeb.AdminService.GetDataToDataSetRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://clinicalsup.jp/")>  _
    Partial Public Class GetDataToDataSetRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public pUserID As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public pInstitutionCode As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public pPassword As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public pSql As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=4)>  _
        Public RtnCD As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public RtnMsg As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal pUserID As String, ByVal pInstitutionCode As String, ByVal pPassword As String, ByVal pSql As String, ByVal RtnCD As Integer, ByVal RtnMsg As String)
            MyBase.New
            Me.pUserID = pUserID
            Me.pInstitutionCode = pInstitutionCode
            Me.pPassword = pPassword
            Me.pSql = pSql
            Me.RtnCD = RtnCD
            Me.RtnMsg = RtnMsg
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetDataToDataSetResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetDataToDataSetResponse", [Namespace]:="http://clinicalsup.jp/", Order:=0)>  _
        Public Body As JpocWeb.AdminService.GetDataToDataSetResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As JpocWeb.AdminService.GetDataToDataSetResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://clinicalsup.jp/")>  _
    Partial Public Class GetDataToDataSetResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetDataToDataSetResult() As Byte
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public RtnCD As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public RtnMsg As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetDataToDataSetResult() As Byte, ByVal RtnCD As Integer, ByVal RtnMsg As String)
            MyBase.New
            Me.GetDataToDataSetResult = GetDataToDataSetResult
            Me.RtnCD = RtnCD
            Me.RtnMsg = RtnMsg
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ExecuteNoResultRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ExecuteNoResult", [Namespace]:="http://clinicalsup.jp/", Order:=0)>  _
        Public Body As JpocWeb.AdminService.ExecuteNoResultRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As JpocWeb.AdminService.ExecuteNoResultRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://clinicalsup.jp/")>  _
    Partial Public Class ExecuteNoResultRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public pUserID As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public pInstitutionCode As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public pPassword As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public pSql As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=4)>  _
        Public RtnCD As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public RtnMsg As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal pUserID As String, ByVal pInstitutionCode As String, ByVal pPassword As String, ByVal pSql As String, ByVal RtnCD As Integer, ByVal RtnMsg As String)
            MyBase.New
            Me.pUserID = pUserID
            Me.pInstitutionCode = pInstitutionCode
            Me.pPassword = pPassword
            Me.pSql = pSql
            Me.RtnCD = RtnCD
            Me.RtnMsg = RtnMsg
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ExecuteNoResultResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ExecuteNoResultResponse", [Namespace]:="http://clinicalsup.jp/", Order:=0)>  _
        Public Body As JpocWeb.AdminService.ExecuteNoResultResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As JpocWeb.AdminService.ExecuteNoResultResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://clinicalsup.jp/")>  _
    Partial Public Class ExecuteNoResultResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public ExecuteNoResultResult As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public RtnCD As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public RtnMsg As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ExecuteNoResultResult As Integer, ByVal RtnCD As Integer, ByVal RtnMsg As String)
            MyBase.New
            Me.ExecuteNoResultResult = ExecuteNoResultResult
            Me.RtnCD = RtnCD
            Me.RtnMsg = RtnMsg
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface AdminServiceSoapChannel
        Inherits JpocWeb.AdminService.AdminServiceSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class AdminServiceSoapClient
        Inherits System.ServiceModel.ClientBase(Of JpocWeb.AdminService.AdminServiceSoap)
        Implements JpocWeb.AdminService.AdminServiceSoap

        Public Sub New()
            MyBase.New
        End Sub

        'TODO: FIX HERE
        Public Sub New(ByVal endpointConfigurationName As String)
            'MyBase.New(endpointConfigurationName)
        End Sub
        'TODO: FIX HERE
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            'MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        'TODO: FIX HERE
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            'MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function JpocWeb_AdminService_AdminServiceSoap_GetDataToDataSet(ByVal request As JpocWeb.AdminService.GetDataToDataSetRequest) As JpocWeb.AdminService.GetDataToDataSetResponse Implements JpocWeb.AdminService.AdminServiceSoap.GetDataToDataSet
            Return MyBase.Channel.GetDataToDataSet(request)
        End Function
        
        Public Function GetDataToDataSet(ByVal pUserID As String, ByVal pInstitutionCode As String, ByVal pPassword As String, ByVal pSql As String, ByRef RtnCD As Integer, ByRef RtnMsg As String) As Byte()
            Dim inValue As JpocWeb.AdminService.GetDataToDataSetRequest = New JpocWeb.AdminService.GetDataToDataSetRequest()
            inValue.Body = New JpocWeb.AdminService.GetDataToDataSetRequestBody()
            inValue.Body.pUserID = pUserID
            inValue.Body.pInstitutionCode = pInstitutionCode
            inValue.Body.pPassword = pPassword
            inValue.Body.pSql = pSql
            inValue.Body.RtnCD = RtnCD
            inValue.Body.RtnMsg = RtnMsg
            Dim retVal As JpocWeb.AdminService.GetDataToDataSetResponse = CType(Me,JpocWeb.AdminService.AdminServiceSoap).GetDataToDataSet(inValue)
            RtnCD = retVal.Body.RtnCD
            RtnMsg = retVal.Body.RtnMsg
            Return retVal.Body.GetDataToDataSetResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function JpocWeb_AdminService_AdminServiceSoap_ExecuteNoResult(ByVal request As JpocWeb.AdminService.ExecuteNoResultRequest) As JpocWeb.AdminService.ExecuteNoResultResponse Implements JpocWeb.AdminService.AdminServiceSoap.ExecuteNoResult
            Return MyBase.Channel.ExecuteNoResult(request)
        End Function
        
        Public Function ExecuteNoResult(ByVal pUserID As String, ByVal pInstitutionCode As String, ByVal pPassword As String, ByVal pSql As String, ByRef RtnCD As Integer, ByRef RtnMsg As String) As Integer
            Dim inValue As JpocWeb.AdminService.ExecuteNoResultRequest = New JpocWeb.AdminService.ExecuteNoResultRequest()
            inValue.Body = New JpocWeb.AdminService.ExecuteNoResultRequestBody()
            inValue.Body.pUserID = pUserID
            inValue.Body.pInstitutionCode = pInstitutionCode
            inValue.Body.pPassword = pPassword
            inValue.Body.pSql = pSql
            inValue.Body.RtnCD = RtnCD
            inValue.Body.RtnMsg = RtnMsg
            Dim retVal As JpocWeb.AdminService.ExecuteNoResultResponse = CType(Me,JpocWeb.AdminService.AdminServiceSoap).ExecuteNoResult(inValue)
            RtnCD = retVal.Body.RtnCD
            RtnMsg = retVal.Body.RtnMsg
            Return retVal.Body.ExecuteNoResultResult
        End Function
    End Class
End Namespace
